# Generated by Django 2.2.1 on 2019-05-28 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20190528_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 18, 27, 57, 906986), verbose_name='date published'),
        ),
    ]
